### ISSUE TITLE
[IMPORTANT] Add server flag: disable ressurection

### ISSUE THREAD

**Issue by igroglaz** [igroglaz/srvmgr#55]
We are designing new quest map progress: each quest map will have only one item at the end.. It will be like a dungeon which you have to go through to get the prize.. And it's only one prize, free for all.

The problem is that some players will be able to steal the prize right under the nose of people who cleared all the way. In general stealing is alright and there is PvP to prevent it, but the problem is that there is possibility for a players to ressurect again and again, teleporting to in vein to get the prize. Even with exp loss some players might consider to ressurect a lot of times just to get an item (as it takes 2 hours to get from 0 exp to 95 skill).

To prevent such behaivour could be such solution:
add server flag "prevent_ressurection"

if this flag is ON on server configuration -> any player won't have possibility to ressurect upon death (so player has to 'alt+f4' and wait 5 minutes, so hat will release his character and player will be able to contunie playing).

It will give feeling of battle-royale for quest maps... "There can be only one" ;)

Atm I see two ways to implement such design:
1) after death disable option to ressurect (push 'space').. so it won't work
2) after death automatically kick player from server and prevent him to login for some time

**Comment by serg-bloim** [comment]
But what about a situation when a player clears the path to the item and he's alone, there is no thief. But if he's got died because of a monster, he'll get out of quest for 5 min. I guess dying on a quest map is a common thing many players practice =)
But it will make doing quests less fun is you have to wait 5 mins. More to that if you died half way to the end, after 5 mins you'll have to start clearing the path from the beginning. And now you can try to TP  and continue from where you died. 

Another concern is that usually quests are team-work. And if you died, you're teammates are still gonna need you and they might also die without your support, or they cannot proceed without you so they also have to wait for 5 mins = no fun.

IMHO there should be a better way how to deal with stealing.

**Comment by igroglaz** [comment]
Yep, this problem won't be a problem as we will have PvP enabled on quests :) It was a problem when we didn't had % loot feature (which you just kindly implemented!). So I'll close this.

**Comment by igroglaz** [comment]
btw just in case... https://web.archive.org/web/20091008052413/http://allods.homeunix.org/article_a2_no_rebirth.php

allods2.exe
0000C296: 7F EB
0000C297: 0D 08
